const hoursInDay = [
  {title: '', key: 'stringNumber', sortable: false},
  {title: '1:00', key: 'h1', sortable: false},
  {title: '2:00', key: 'h2', sortable: false},
  {title: '3:00', key: 'h3', sortable: false},
  {title: '4:00', key: 'h4', sortable: false},
  {title: '5:00', key: 'h5', sortable: false},
  {title: '6:00', key: 'h6', sortable: false},
  {title: '7:00', key: 'h7', sortable: false},
  {title: '8:00', key: 'h8', sortable: false},
  {title: '9:00', key: 'h9', sortable: false},
  {title: '10:00', key: 'h10', sortable: false},
  {title: '11:00', key: 'h11', sortable: false},
  {title: '12:00', key: 'h12', sortable: false},
  {title: '13:00', key: 'h13', sortable: false},
  {title: '14:00', key: 'h14', sortable: false},
  {title: '15:00', key: 'h15', sortable: false},
  {title: '16:00', key: 'h16', sortable: false},
  {title: '17:00', key: 'h17', sortable: false},
  {title: '18:00', key: 'h18', sortable: false},
  {title: '19:00', key: 'h19', sortable: false},
  {title: '20:00', key: 'h20', sortable: false},
  {title: '21:00', key: 'h21', sortable: false},
  {title: '22:00', key: 'h22', sortable: false},
  {title: '23:00', key: 'h23', sortable: false},
  {title: '24:00', key: 'h24', sortable: false},
];

const daysInMonth = [
  {title: '', key: 'first', sortable: false},
  {title: '1', key: 'd1', sortable: false},
  {title: '2', key: 'd2', sortable: false},
  {title: '3', key: 'd3', sortable: false},
  {title: '4', key: 'd4', sortable: false},
  {title: '5', key: 'd5', sortable: false},
  {title: '6', key: 'd6', sortable: false},
  {title: '7', key: 'd7', sortable: false},
  {title: '8', key: 'd8', sortable: false},
  {title: '9', key: 'd9', sortable: false},
  {title: '10', key: 'd10', sortable: false},
  {title: '11', key: 'd11', sortable: false},
  {title: '12', key: 'd12', sortable: false},
  {title: '13', key: 'd13', sortable: false},
  {title: '14', key: 'd14', sortable: false},
  {title: '15', key: 'd15', sortable: false},
  {title: '16', key: 'd16', sortable: false},
  {title: '17', key: 'd17', sortable: false},
  {title: '18', key: 'd18', sortable: false},
  {title: '19', key: 'd19', sortable: false},
  {title: '20', key: 'd20', sortable: false},
  {title: '21', key: 'd21', sortable: false},
  {title: '22', key: 'd22', sortable: false},
  {title: '23', key: 'd23', sortable: false},
  {title: '24', key: 'd24', sortable: false},
  {title: '25', key: 'd25', sortable: false},
  {title: '26', key: 'd26', sortable: false},
  {title: '27', key: 'd27', sortable: false},
  {title: '28', key: 'd28', sortable: false},
  {title: '29', key: 'd29', sortable: false},
  {title: '30', key: 'd30', sortable: false},
];

export {
  hoursInDay,
  daysInMonth
}